INSERT INTO tb_game_list (name) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (name) VALUES ('Jogos de Plataforma');

INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'A épica trilogia sci-fi que mistura RPG e ação shooter, conduzindo o jogador por uma galáxia ameaçada por forças sombrias.', 'Mass Effect Trilogy é uma jornada envolvente no espaço onde suas escolhas moldam a narrativa, explorando planetas diversos, liderando uma equipe única e combatendo ameaças intergalácticas em batalhas estratégicas. A combinação de elementos de RPG e ação shooter redefine o gênero, oferecendo uma experiência profunda e memorável.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'Uma aventura épica no velho oeste americano, com um enredo dramático e um mundo aberto impressionante para explorar.', 'Red Dead Redemption 2 oferece uma narrativa rica e emocional, focada na vida de Arthur Morgan e sua gangue. O jogo mistura ação, exploração e interações realistas em um cenário imersivo, capturando a essência da fronteira americana com detalhes incríveis e um roteiro envolvente.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'Um RPG de ação aclamado pela crítica, ambientado em um mundo aberto cheio de monstros, magia e escolhas morais complexas.', 'The Witcher 3: Wild Hunt apresenta Geralt de Rívia, um caçador de monstros em uma jornada épica para encontrar sua filha adotiva. O jogo é conhecido por sua narrativa profunda, missões secundárias complexas e um mundo vibrante que responde às decisões do jogador, tornando cada aventura única.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'Um desafiante jogo de ação e aventura ambientado no Japão feudal, focado em combates precisos e furtividade.', 'Sekiro: Shadows Die Twice coloca o jogador na pele de um shinobi habilidoso que enfrenta inimigos formidáveis em um mundo implacável. O jogo destaca-se pela sua dificuldade elevada, combate tático e mecânicas de furtividade, oferecendo uma experiência intensa e recompensadora.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2012, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Uma aventura samurai em mundo aberto que captura a beleza e brutalidade do Japão feudal.', 'Ghost of Tsushima narra a luta de Jin Sakai para defender sua terra contra invasores mongóis. Com gráficos impressionantes e combates refinados, o jogo oferece liberdade para explorar, lutar e se tornar uma lenda samurai em um cenário autêntico e cativante.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'O clássico jogo de plataforma que definiu gerações com níveis criativos e controles precisos.', 'Super Mario World é um marco dos jogos de plataforma, apresentando Mario e Luigi em uma aventura para salvar a Princesa Peach. Com mundos coloridos, power-ups icônicos e desafios divertidos, é um título atemporal que influenciou inúmeros jogos do gênero.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'Um metroidvania sombrio e desafiador, com uma atmosfera profunda e exploração não-linear.', 'Hollow Knight apresenta um mundo subterrâneo vasto e misterioso, repleto de criaturas únicas e segredos ocultos. O jogo combina combate ágil, habilidades evolutivas e design artístico detalhado, proporcionando uma experiência de plataforma intensa e imersiva.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4, 2015, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'Um belo jogo de plataforma com ênfase em narrativa emocional e visuais deslumbrantes.', 'Ori and the Blind Forest conta a tocante história de Ori, um espírito guardião, em um mundo mágico ameaçado pela destruição. Com gameplay fluido, quebra-cabeças inteligentes e uma trilha sonora envolvente, é uma aventura que combina emoção e desafio.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'Um jogo de plataforma com estética dos desenhos animados clássicos e um nível de dificuldade elevado.', 'Cuphead destaca-se pelo seu visual inspirado em animações dos anos 1930, gameplay frenético e chefes desafiadores. Com uma trilha sonora jazz vibrante e animações desenhadas à mão, o jogo combina arte e ação para uma experiência única.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic CD', 4, 1993, 'Platform', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'Um clássico jogo de plataforma que apresenta o ouriço azul em uma aventura rápida e cheia de loops.', 'Sonic CD é conhecido por sua jogabilidade veloz, trilha sonora marcante e design inovador de fases. O jogo introduz viagens no tempo como mecânica principal, permitindo que Sonic explore versões passadas e futuras de cada estágio, garantindo uma experiência dinâmica e divertida.');

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 5, 4);

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 10, 4);